#!/usr/bin/env python3
"""Write the list of where the source of every package in the image is.

Usage: source-manifest.py <packages.tsv> <output.md> <version>

The binaries are redistributed unmodified apart from the text the debranding
edits, so the corresponding source is pointed to rather than copied: Debian
keeps every source package it ever published on snapshot.debian.org, and VyOS
publishes its sources as Git repositories rather than as source packages. A
package is attributed to VyOS when the rolling repository carries that exact
binary version; everything else came from Debian.
"""
import gzip
import os
import re
import sys
import urllib.parse
import urllib.request

tsv, out, version = sys.argv[1], sys.argv[2], sys.argv[3]
mirror = os.environ["VYOS_MIRROR"]
arch = os.environ["ARCH"]
ref = os.environ["VYOS_BUILD_REF"]
image = os.environ["VYOS_BUILD_IMAGE"]

# The index captured when the build started (VYOS_INDEX), so a version the
# repository replaced during the build is still recognised; the mirror only
# when the script runs on its own.
if os.environ.get("VYOS_INDEX"):
    with open(os.environ["VYOS_INDEX"], "rb") as f:
        index = gzip.decompress(f.read()).decode("utf-8", "replace")
else:
    req = urllib.request.Request(
        f"{mirror}/dists/rolling/main/binary-{arch}/Packages.gz",
        headers={"User-Agent": "barerouter-build"},
    )
    with urllib.request.urlopen(req) as r:
        index = gzip.decompress(r.read()).decode("utf-8", "replace")
vyos = set()
name = None
for line in index.splitlines():
    if line.startswith("Package: "):
        name = line.split(": ", 1)[1]
    elif line.startswith("Version: ") and name:
        vyos.add((name, line.split(": ", 1)[1]))

rows = []
with open(tsv, encoding="utf-8") as f:
    for line in f:
        pkg, ver, src, srcver = (line.rstrip("\n").split("\t") + ["", "", "", ""])[:4]
        rows.append((pkg, ver, src or pkg, srcver or ver))
if not rows:
    sys.exit(f"E: {tsv} lists no packages")

debian, from_vyos, binary_versions = {}, {}, {}
for pkg, ver, src, srcver in rows:
    target = from_vyos if (pkg, ver) in vyos else debian
    target.setdefault((src, srcver), []).append(pkg)
    binary_versions.setdefault((src, srcver), []).append(ver)

build_tree = f"https://github.com/vyos/vyos-build/tree/{ref}"
lines = [
    f"# Sources for barerouter {version}",
    "",
    f"This image is built by [barerouter](https://github.com/aenix-io/barerouter) at tag `v{version}`, from [vyos/vyos-build]({build_tree}) at `{ref}` inside `{image}`. The only changes made to upstream files are the debranding edits, which are generated by `hack/debrand-tree.py` and `debrand/chroot/99-barerouter-debrand.chroot` in that tag.",
    "",
    f"## From the VyOS rolling repository ({len(from_vyos)} source packages)",
    "",
    f"VyOS publishes its sources as Git repositories rather than as source packages. Two files published with this release pin them: `barerouter-{version}-{arch}.vyos-build.tar.gz` is the vyos-build tree the image was built from, with every `scripts/package-build` definition, patch, kernel configuration and build script, and `barerouter-{version}-{arch}.refs.lock` resolves every upstream repository and reference in it, and every VyOS repository the image takes a package from, to the commit it named on the day of the build. The kernel is the kernel.org release named there with the patches and configuration under `scripts/package-build/linux-kernel`. Where a version below carries a commit (`-g<hash>` or `+g<hash>`), that is the commit the package was built from.",
    "",
    "| Source package | Version | Binary packages |",
    "| --- | --- | --- |",
]
for (src, srcver), pkgs in sorted(from_vyos.items()):
    # The source version can drop the describe suffix the binary carries
    # (vyos-1x is 999.0 as a source and 999.0-<n>-g<commit> as a binary).
    commit = None
    for v in [srcver] + binary_versions[(src, srcver)]:
        commit = re.search(r"[-+]g([0-9a-f]{7,40})$", v)
        if commit:
            break
    shown = f"`{srcver}` (commit `{commit.group(1)}`)" if commit else f"`{srcver}`"
    lines.append(f"| `{src}` | {shown} | {', '.join(sorted(pkgs))} |")
lines += [
    "",
    f"## From Debian ({len(debian)} source packages)",
    "",
    "Each link is the snapshot.debian.org page of that exact source version.",
    "",
    "| Source package | Version |",
    "| --- | --- |",
]
for (src, srcver) in sorted(debian):
    link = f"https://snapshot.debian.org/package/{src}/{urllib.parse.quote(srcver)}/"
    lines.append(f"| [`{src}`]({link}) | `{srcver}` |")

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"I: {len(from_vyos)} VyOS and {len(debian)} Debian source packages listed in {out}")
